#!/usr/bin/python3

import sys
import time


def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True


def find_prime_factors(n):
    for i in range(2, n):
        if is_prime(i) and n % i == 0:
            return i, n // i
    return None, None


def main(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            start_time = time.time()
            p, q = find_prime_factors(number)
            elapsed_time = time.time() - start_time

            if p is not None and q is not None:
                print(f"{number} = {p} * {q}")
            else:
                print(f"Unable to find prime factors for {number}")

            
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: prime_factors <file>")
        sys.exit(1)

    filename = sys.argv[1]
    main(filename)
